version: "3.9"

services:
  GameApp-database:
    image: mysql:oraclelinux9
    container_name: gameApp-Database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: suggest
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

volumes:
  mysql_data:
